name: "Create Repository with Lambda Template"
description: "Creates a GitHub repository from a template with Lambda code and deployment workflows"
inputs:
  repo-name:
    description: "The name of the new repository"
    required: true
  template-url:
    description: "URL of the template repository"
    required: true
  org:
    description: "Organization or username for the repository"
    required: true
  github-token:
    description: "GitHub Token for authentication"
    required: true
runs:
  using: "composite"
  steps:
    - name: Create Repository from Template
      uses: actions/github-script@v6
      with:
        script: |
          const core = require('@actions/core');

          // Get inputs
          const templateUrl = core.getInput('template-url');
          const repoName = core.getInput('repo-name');
          const org = core.getInput('org');

          // Extract owner and repo from template URL
          const [owner, repo] = templateUrl.replace('https://github.com/', '').split('/');

          try {
            const response = await github.rest.repos.createUsingTemplate({
              template_owner: owner,
              template_repo: repo,
              name: repoName,
              owner: org,
              private: false,
            });

            // Set output with the new repository URL
            core.setOutput("repo-url", response.data.html_url);
          } catch (error) {
            core.setFailed(`Failed to create repository: ${error.message}`);
          }
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
