name: "Create Repository with Lambda Template"
description: "Creates a GitHub repository from a template with Lambda code and deployment workflows"
inputs:
  repo-name:
    description: "The name of the new repository"
    required: true
    default: ""
  template-url:
    description: "URL of the template repository"
    required: true
    default: ""
  org:
    description: "Organization or username for the repository"
    required: true
    default: ""
  github-token:
    description: "GitHub Token for authentication"
    required: true
outputs:
  repo-url:
    description: "URL of the newly created repository"
    value: ${{ steps.create-repo.outputs.repo-url }}

runs:
  using: "composite"
  steps:
    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      shell: bash

    - name: Create Repository from Template
      run: |
        gh repo create ${{ inputs.org }}/${{ inputs.repo-name }} --template "${{ inputs.template-url }}" --public
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
