name: "Create Repository with Lambda Template"
description: "Creates a GitHub repository from a template with Lambda code and deployment workflows"
inputs:
  repo-name:
    description: "The name of the new repository"
    required: true
  template-url:
    description: "URL of the template repository"
    required: true
  org:
    description: "Organization or username for the repository"
    required: true
  github-token:
    description: "GitHub Token for authentication"
    required: true
runs:
  using: "composite"
  steps:
    - name: Create Repository from Template
      uses: actions/github-script@v6
      with:
        script: |
          const [owner, repo] = '${{ inputs.template-url }}'.replace('https://github.com/', '').split('/');
          const newRepo = await github.repos.createUsingTemplate({
            template_owner: owner,
            template_repo: repo,
            name: '${{ inputs.repo-name }}',
            owner: '${{ inputs.org }}',
            private: false,
          });
          core.setOutput("repo-url", newRepo.data.html_url);
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
