name: Create Lambda Repository

on:
  workflow_dispatch:

jobs:
  create-repo:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Use Composite Action
        uses: zzfernando/custom-actions-poc@main
        with:
          repo-name: "lambda-repo-test"
          template-url: "https://github.com/zzfernando/custom-actions-poc/templates"
          org: "zzfernando"
          github-token: ${{ secrets.ACTIONS_SECRET }}
